name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: dev
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo test
